- name: installing multiple pacakges 
  hosts: web
  become: yes 
  tasks:
  - name: installing multiple packges throgh loops
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop  :
    - mysql
    - gcc
    - zip
    - git   
