- name: filters
  hosts: web
  become: yes 
  tasks:
  - name: variable filetering
    ansible.builtin.debug:
      msg: "Hello Goodmng {{ person | default('veera') }}"

 -  name: converting to string to list
    vars:
     frutis: " apple, mango, bananna "
    ansible.builtin.debug:
      msg: "Fruits are {{ frutis }}"
