- name: filters
  hosts: web
  become: yes 
  tasks:
  - name: converting to string to list
    vars:
     frutis: " apple, mango, bananna "
    ansible.builtin.debug:
      msg: "Fruits are {{ frutis | split (',') }}"
  
  - name: convert  map into list
    vars:
      course:
       name: ansible
       duration: 10hrs
       trianier: sivakumar
    ansible.builtin.debug:
      msg: "course info :{{ course |dict2items }}"

   - name: convert list to map
     vars:
       course:
       - {'key': 'name', 'value': 'ansible'}
       - {'key': 'duration', 'value': '10hrs'}
       - {'key': 'trianier', 'value': 'sivakumar'} 
     ansible.builtin.debug:
       msg: "couse info :{{ course | items2dict }}"     
       