- name: filters
  hosts: web
  become: yes 
  tasks:
  - name: converting to string to list
    vars:
     frutis: " apple, mango, bananna "
    ansible.builtin.debug:
      msg: "Fruits are {{ frutis | split (',') }}"
  
  - name: convert  map into list
    vars:
      course:
       name: ansible
       duration: 10hrs
       trianier: sivakumar
    ansible.builtin.debug:
      msg: "course info :{{ course |dict2items }}"

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trianier', 'value': 'sivakumar'} 
    ansible.builtin.debug:
      msg: "couse info :{{ course | items2dict }}" 

  - name: convert to upper to lower        
    vars:   
      name: "Y VEERABABU"
    ansible.builtin.debug:   
      msg: " converting to lower {{ name | lower }}"

  - name: convert to LOWER to UPPER
    vars:
      name: y veerababu
    ansible.builtin.debug:
      msg: "conveting to UPPER {{ name | upper }}"  


  - name: checking min and maxmium
    vars:
      number: [1,5,7,8,25,75,100,] 
    ansible.builtin.debug:
      msg: "min :{{ number | min }}  max: {{ number | max  }}" 

  - name: check ip address is valid or not
    vars:
      ip: 192.68.1.1
    ansible.builtin.debug:
      msg: "{{ ip |ansible.utils.ipaddr }}"

