- name: checking ansible command module
  hosts: local
  connection: local
  tasks:
  - name: using anisble command module
    #ansible.builtin.command: ls -ltr > /tmp/filesyststem.txt
    ansible.builtin.shell: ls -ltr > /tmp/filesyststem.txt
  
  - name: using command module
    ansible.builtin.command: 'df -h' 
    register: command_output

  - name: print the output 
    ansible.builtin.debug:
      msg: "ping the {{ command_output }}" 

  - name: Check Disk Usage Example
    hosts: local
    tasks:
    - name: Check disk space
      ansible.builtin.shell: df -h
      register: disk_usage
       
     