- name: checking ansible command module
  hosts: local
  connection: local
  tasks:
  - name: using anisble command module
    #ansible.builtin.command: ls -ltr > /tmp/filesyststem.txt
    ansible.builtin.shell: ls -ltr > /tmp/filesyststem.txt
  
  - name: using command module
    ansible.builtin.command: ls -ltr 
    register: command_output

   -name: print the output 
    ansible.builtin.debug:
      msg: "ping the {{ command_output }}" 
     